/**
 * Static require map for all Creepy Creatures PNGs.
 * Generated — do not edit by hand.
 * Metro bundler requires explicit require() calls per asset.
 */
import { ImageSourcePropType } from 'react-native';

export const CREATURE_IMAGES: Record<string, ImageSourcePropType> = {
  'creepy-creatures-africanized-honeybee': require('./creepy-creatures-africanized-honeybee.png'),
  'creepy-creatures-asian-giant-hornet': require('./creepy-creatures-asian-giant-hornet.png'),
  'creepy-creatures-assassin-bug': require('./creepy-creatures-assassin-bug.png'),
  'creepy-creatures-australian-funnel-web-spider': require('./creepy-creatures-australian-funnel-web-spider.png'),
  'creepy-creatures-aye-aye': require('./creepy-creatures-aye-aye.png'),
  'creepy-creatures-bat-eating-centipede': require('./creepy-creatures-bat-eating-centipede.png'),
  'creepy-creatures-black-dragonfish': require('./creepy-creatures-black-dragonfish.png'),
  'creepy-creatures-black-swallower': require('./creepy-creatures-black-swallower.png'),
  'creepy-creatures-blue-dragon-sea-slug': require('./creepy-creatures-blue-dragon-sea-slug.png'),
  'creepy-creatures-blue-ringed-octopus': require('./creepy-creatures-blue-ringed-octopus.png'),
  'creepy-creatures-bombardier-beetle': require('./creepy-creatures-bombardier-beetle.png'),
  'creepy-creatures-botfly-larva': require('./creepy-creatures-botfly-larva.png'),
  'creepy-creatures-brain-worm': require('./creepy-creatures-brain-worm.png'),
  'creepy-creatures-bristle-worm': require('./creepy-creatures-bristle-worm.png'),
  'creepy-creatures-bullet-ant': require('./creepy-creatures-bullet-ant.png'),
  'creepy-creatures-candiru-fish': require('./creepy-creatures-candiru-fish.png'),
  'creepy-creatures-cassowary': require('./creepy-creatures-cassowary.png'),
  'creepy-creatures-cone-snail': require('./creepy-creatures-cone-snail.png'),
  'creepy-creatures-deathstalker-scorpion': require('./creepy-creatures-deathstalker-scorpion.png'),
  'creepy-creatures-deep-sea-lizardfish': require('./creepy-creatures-deep-sea-lizardfish.png'),
  'creepy-creatures-electric-eel': require('./creepy-creatures-electric-eel.png'),
  'creepy-creatures-eyeless-spider': require('./creepy-creatures-eyeless-spider.png'),
  'creepy-creatures-flesh-fly': require('./creepy-creatures-flesh-fly.png'),
  'creepy-creatures-flying-snake': require('./creepy-creatures-flying-snake.png'),
  'creepy-creatures-gharial': require('./creepy-creatures-gharial.png'),
  'creepy-creatures-giant-isopod': require('./creepy-creatures-giant-isopod.png'),
  'creepy-creatures-goblin-shark': require('./creepy-creatures-goblin-shark.png'),
  'creepy-creatures-goliath-birdeater': require('./creepy-creatures-goliath-birdeater.png'),
  'creepy-creatures-goliath-tigerfish': require('./creepy-creatures-goliath-tigerfish.png'),
  'creepy-creatures-guinea-worm': require('./creepy-creatures-guinea-worm.png'),
  'creepy-creatures-hag-moth-caterpillar': require('./creepy-creatures-hag-moth-caterpillar.png'),
  'creepy-creatures-hagfish': require('./creepy-creatures-hagfish.png'),
  'creepy-creatures-hammerhead-worm': require('./creepy-creatures-hammerhead-worm.png'),
  'creepy-creatures-harlequin-toad': require('./creepy-creatures-harlequin-toad.png'),
  'creepy-creatures-hooded-pitohui': require('./creepy-creatures-hooded-pitohui.png'),
  'creepy-creatures-horse-botfly': require('./creepy-creatures-horse-botfly.png'),
  'creepy-creatures-horsehair-worm': require('./creepy-creatures-horsehair-worm.png'),
  'creepy-creatures-hypnotic-stargazer-worm': require('./creepy-creatures-hypnotic-stargazer-worm.png'),
  'creepy-creatures-immortal-jellyfish': require('./creepy-creatures-immortal-jellyfish.png'),
  'creepy-creatures-inland-taipan': require('./creepy-creatures-inland-taipan.png'),
  'creepy-creatures-japanese-spider-crab': require('./creepy-creatures-japanese-spider-crab.png'),
  'creepy-creatures-kissing-bug': require('./creepy-creatures-kissing-bug.png'),
  'creepy-creatures-komodo-dragon': require('./creepy-creatures-komodo-dragon.png'),
  'creepy-creatures-lamprey': require('./creepy-creatures-lamprey.png'),
  'creepy-creatures-maggot-of-the-flesh-fly': require('./creepy-creatures-maggot-of-the-flesh-fly.png'),
  'creepy-creatures-mouth-brooding-fish': require('./creepy-creatures-mouth-brooding-fish.png'),
  'creepy-creatures-musk-ox-parasite-fly': require('./creepy-creatures-musk-ox-parasite-fly.png'),
  'creepy-creatures-nose-horned-viper': require('./creepy-creatures-nose-horned-viper.png'),
  'creepy-creatures-parasitic-barnacle': require('./creepy-creatures-parasitic-barnacle.png'),
  'creepy-creatures-peacock-mantis-shrimp': require('./creepy-creatures-peacock-mantis-shrimp.png'),
  'creepy-creatures-pistol-shrimp': require('./creepy-creatures-pistol-shrimp.png'),
  'creepy-creatures-poison-dart-frog': require('./creepy-creatures-poison-dart-frog.png'),
  'creepy-creatures-rat-tailed-maggot': require('./creepy-creatures-rat-tailed-maggot.png'),
  'creepy-creatures-red-paper-wasp': require('./creepy-creatures-red-paper-wasp.png'),
  'creepy-creatures-saddleback-caterpillar': require('./creepy-creatures-saddleback-caterpillar.png'),
  'creepy-creatures-scaly-foot-snail': require('./creepy-creatures-scaly-foot-snail.png'),
  'creepy-creatures-sea-cucumber': require('./creepy-creatures-sea-cucumber.png'),
  'creepy-creatures-sea-devil-anglerfish': require('./creepy-creatures-sea-devil-anglerfish.png'),
  'creepy-creatures-sea-spider': require('./creepy-creatures-sea-spider.png'),
  'creepy-creatures-spiny-oak-slug-caterpillar': require('./creepy-creatures-spiny-oak-slug-caterpillar.png'),
  'creepy-creatures-stargazer-fish': require('./creepy-creatures-stargazer-fish.png'),
  'creepy-creatures-stink-bug': require('./creepy-creatures-stink-bug.png'),
  'creepy-creatures-stonefish': require('./creepy-creatures-stonefish.png'),
  'creepy-creatures-surinam-toad': require('./creepy-creatures-surinam-toad.png'),
  'creepy-creatures-terrible-claw-lobster': require('./creepy-creatures-terrible-claw-lobster.png'),
  'creepy-creatures-tiger-leech': require('./creepy-creatures-tiger-leech.png'),
  'creepy-creatures-tongue-worm': require('./creepy-creatures-tongue-worm.png'),
  'creepy-creatures-tongue-eating-louse': require('./creepy-creatures-tongue-eating-louse.png'),
  'creepy-creatures-tsetse-fly': require('./creepy-creatures-tsetse-fly.png'),
  'creepy-creatures-vampire-bat': require('./creepy-creatures-vampire-bat.png'),
  'creepy-creatures-vampire-fish-payara': require('./creepy-creatures-vampire-fish-payara.png'),
  'creepy-creatures-velvet-worm': require('./creepy-creatures-velvet-worm.png'),
  'creepy-creatures-zombie-ant-fungus': require('./creepy-creatures-zombie-ant-fungus.png'),
  'creepy-creatures-zombie-snail': require('./creepy-creatures-zombie-snail.png'),
  'creepy-creatures-zombie-starfish': require('./creepy-creatures-zombie-starfish.png'),
};
