/**
 * Static require map for all Creepy Creatures PNGs.
 * Generated — do not edit by hand.
 *
 * Kept in constants/ (not assets/) so Metro transforms the TypeScript correctly.
 * require() paths are relative to this file's location in constants/.
 */
import { ImageSourcePropType } from 'react-native';

export const CREATURE_IMAGES: Record<string, ImageSourcePropType> = {
  'creepy-creatures-africanized-honeybee': require('../assets/creatures/creepy-creatures-africanized-honeybee.png'),
  'creepy-creatures-asian-giant-hornet': require('../assets/creatures/creepy-creatures-asian-giant-hornet.png'),
  'creepy-creatures-assassin-bug': require('../assets/creatures/creepy-creatures-assassin-bug.png'),
  'creepy-creatures-australian-funnel-web-spider': require('../assets/creatures/creepy-creatures-australian-funnel-web-spider.png'),
  'creepy-creatures-aye-aye': require('../assets/creatures/creepy-creatures-aye-aye.png'),
  'creepy-creatures-bat-eating-centipede': require('../assets/creatures/creepy-creatures-bat-eating-centipede.png'),
  'creepy-creatures-black-dragonfish': require('../assets/creatures/creepy-creatures-black-dragonfish.png'),
  'creepy-creatures-black-swallower': require('../assets/creatures/creepy-creatures-black-swallower.png'),
  'creepy-creatures-blue-dragon-sea-slug': require('../assets/creatures/creepy-creatures-blue-dragon-sea-slug.png'),
  'creepy-creatures-blue-ringed-octopus': require('../assets/creatures/creepy-creatures-blue-ringed-octopus.png'),
  'creepy-creatures-bombardier-beetle': require('../assets/creatures/creepy-creatures-bombardier-beetle.png'),
  'creepy-creatures-botfly-larva': require('../assets/creatures/creepy-creatures-botfly-larva.png'),
  'creepy-creatures-brain-worm': require('../assets/creatures/creepy-creatures-brain-worm.png'),
  'creepy-creatures-bristle-worm': require('../assets/creatures/creepy-creatures-bristle-worm.png'),
  'creepy-creatures-bullet-ant': require('../assets/creatures/creepy-creatures-bullet-ant.png'),
  'creepy-creatures-candiru-fish': require('../assets/creatures/creepy-creatures-candiru-fish.png'),
  'creepy-creatures-cassowary': require('../assets/creatures/creepy-creatures-cassowary.png'),
  'creepy-creatures-cone-snail': require('../assets/creatures/creepy-creatures-cone-snail.png'),
  'creepy-creatures-deathstalker-scorpion': require('../assets/creatures/creepy-creatures-deathstalker-scorpion.png'),
  'creepy-creatures-deep-sea-lizardfish': require('../assets/creatures/creepy-creatures-deep-sea-lizardfish.png'),
  'creepy-creatures-electric-eel': require('../assets/creatures/creepy-creatures-electric-eel.png'),
  'creepy-creatures-eyeless-spider': require('../assets/creatures/creepy-creatures-eyeless-spider.png'),
  'creepy-creatures-flesh-fly': require('../assets/creatures/creepy-creatures-flesh-fly.png'),
  'creepy-creatures-flying-snake': require('../assets/creatures/creepy-creatures-flying-snake.png'),
  'creepy-creatures-gharial': require('../assets/creatures/creepy-creatures-gharial.png'),
  'creepy-creatures-giant-isopod': require('../assets/creatures/creepy-creatures-giant-isopod.png'),
  'creepy-creatures-goblin-shark': require('../assets/creatures/creepy-creatures-goblin-shark.png'),
  'creepy-creatures-goliath-birdeater': require('../assets/creatures/creepy-creatures-goliath-birdeater.png'),
  'creepy-creatures-goliath-tigerfish': require('../assets/creatures/creepy-creatures-goliath-tigerfish.png'),
  'creepy-creatures-guinea-worm': require('../assets/creatures/creepy-creatures-guinea-worm.png'),
  'creepy-creatures-hag-moth-caterpillar': require('../assets/creatures/creepy-creatures-hag-moth-caterpillar.png'),
  'creepy-creatures-hagfish': require('../assets/creatures/creepy-creatures-hagfish.png'),
  'creepy-creatures-hammerhead-worm': require('../assets/creatures/creepy-creatures-hammerhead-worm.png'),
  'creepy-creatures-harlequin-toad': require('../assets/creatures/creepy-creatures-harlequin-toad.png'),
  'creepy-creatures-hooded-pitohui': require('../assets/creatures/creepy-creatures-hooded-pitohui.png'),
  'creepy-creatures-horse-botfly': require('../assets/creatures/creepy-creatures-horse-botfly.png'),
  'creepy-creatures-horsehair-worm': require('../assets/creatures/creepy-creatures-horsehair-worm.png'),
  'creepy-creatures-hypnotic-stargazer-worm': require('../assets/creatures/creepy-creatures-hypnotic-stargazer-worm.png'),
  'creepy-creatures-immortal-jellyfish': require('../assets/creatures/creepy-creatures-immortal-jellyfish.png'),
  'creepy-creatures-inland-taipan': require('../assets/creatures/creepy-creatures-inland-taipan.png'),
  'creepy-creatures-japanese-spider-crab': require('../assets/creatures/creepy-creatures-japanese-spider-crab.png'),
  'creepy-creatures-kissing-bug': require('../assets/creatures/creepy-creatures-kissing-bug.png'),
  'creepy-creatures-komodo-dragon': require('../assets/creatures/creepy-creatures-komodo-dragon.png'),
  'creepy-creatures-lamprey': require('../assets/creatures/creepy-creatures-lamprey.png'),
  'creepy-creatures-maggot-of-the-flesh-fly': require('../assets/creatures/creepy-creatures-maggot-of-the-flesh-fly.png'),
  'creepy-creatures-mouth-brooding-fish': require('../assets/creatures/creepy-creatures-mouth-brooding-fish.png'),
  'creepy-creatures-musk-ox-parasite-fly': require('../assets/creatures/creepy-creatures-musk-ox-parasite-fly.png'),
  'creepy-creatures-nose-horned-viper': require('../assets/creatures/creepy-creatures-nose-horned-viper.png'),
  'creepy-creatures-parasitic-barnacle': require('../assets/creatures/creepy-creatures-parasitic-barnacle.png'),
  'creepy-creatures-peacock-mantis-shrimp': require('../assets/creatures/creepy-creatures-peacock-mantis-shrimp.png'),
  'creepy-creatures-pistol-shrimp': require('../assets/creatures/creepy-creatures-pistol-shrimp.png'),
  'creepy-creatures-poison-dart-frog': require('../assets/creatures/creepy-creatures-poison-dart-frog.png'),
  'creepy-creatures-rat-tailed-maggot': require('../assets/creatures/creepy-creatures-rat-tailed-maggot.png'),
  'creepy-creatures-red-paper-wasp': require('../assets/creatures/creepy-creatures-red-paper-wasp.png'),
  'creepy-creatures-saddleback-caterpillar': require('../assets/creatures/creepy-creatures-saddleback-caterpillar.png'),
  'creepy-creatures-scaly-foot-snail': require('../assets/creatures/creepy-creatures-scaly-foot-snail.png'),
  'creepy-creatures-sea-cucumber': require('../assets/creatures/creepy-creatures-sea-cucumber.png'),
  'creepy-creatures-sea-devil-anglerfish': require('../assets/creatures/creepy-creatures-sea-devil-anglerfish.png'),
  'creepy-creatures-sea-spider': require('../assets/creatures/creepy-creatures-sea-spider.png'),
  'creepy-creatures-spiny-oak-slug-caterpillar': require('../assets/creatures/creepy-creatures-spiny-oak-slug-caterpillar.png'),
  'creepy-creatures-stargazer-fish': require('../assets/creatures/creepy-creatures-stargazer-fish.png'),
  'creepy-creatures-stink-bug': require('../assets/creatures/creepy-creatures-stink-bug.png'),
  'creepy-creatures-stonefish': require('../assets/creatures/creepy-creatures-stonefish.png'),
  'creepy-creatures-surinam-toad': require('../assets/creatures/creepy-creatures-surinam-toad.png'),
  'creepy-creatures-terrible-claw-lobster': require('../assets/creatures/creepy-creatures-terrible-claw-lobster.png'),
  'creepy-creatures-tiger-leech': require('../assets/creatures/creepy-creatures-tiger-leech.png'),
  'creepy-creatures-tongue-worm': require('../assets/creatures/creepy-creatures-tongue-worm.png'),
  'creepy-creatures-tongue-eating-louse': require('../assets/creatures/creepy-creatures-tongue-eating-louse.png'),
  'creepy-creatures-tsetse-fly': require('../assets/creatures/creepy-creatures-tsetse-fly.png'),
  'creepy-creatures-vampire-bat': require('../assets/creatures/creepy-creatures-vampire-bat.png'),
  'creepy-creatures-vampire-fish-payara': require('../assets/creatures/creepy-creatures-vampire-fish-payara.png'),
  'creepy-creatures-velvet-worm': require('../assets/creatures/creepy-creatures-velvet-worm.png'),
  'creepy-creatures-zombie-ant-fungus': require('../assets/creatures/creepy-creatures-zombie-ant-fungus.png'),
  'creepy-creatures-zombie-snail': require('../assets/creatures/creepy-creatures-zombie-snail.png'),
  'creepy-creatures-zombie-starfish': require('../assets/creatures/creepy-creatures-zombie-starfish.png'),
};
