/**
 * Static require map for all creature images across all three books + special specimens.
 *
 * Metro requires static require() calls — no dynamic paths.
 * Relative to this file's location in constants/.
 *
 * Books:
 *   Creepy Creatures  — assets/creatures/{kebab-id}.png       (75 entries)
 *   Creepy Dinosaurs  — assets/creatures/dinosaurs/{Title}.{ext}  (80 entries)
 *   Creepy Earth      — assets/creatures/earth/{Title}.{ext}      (79 entries)
 *   Special Specimens — assets/creatures/special/{Title}.jpeg     (15 entries)
 */
import { ImageSourcePropType } from 'react-native';

export const CREATURE_IMAGES: Record<string, ImageSourcePropType> = {

  // ─── Creepy Creatures (75) ────────────────────────────────────────────────
  'creepy-creatures-africanized-honeybee': require('../assets/creatures/creepy-creatures-africanized-honeybee.png'),
  'creepy-creatures-asian-giant-hornet': require('../assets/creatures/creepy-creatures-asian-giant-hornet.png'),
  'creepy-creatures-assassin-bug': require('../assets/creatures/creepy-creatures-assassin-bug.png'),
  'creepy-creatures-australian-funnel-web-spider': require('../assets/creatures/creepy-creatures-australian-funnel-web-spider.png'),
  'creepy-creatures-aye-aye': require('../assets/creatures/creepy-creatures-aye-aye.png'),
  'creepy-creatures-bat-eating-centipede': require('../assets/creatures/creepy-creatures-bat-eating-centipede.png'),
  'creepy-creatures-black-dragonfish': require('../assets/creatures/creepy-creatures-black-dragonfish.png'),
  'creepy-creatures-black-swallower': require('../assets/creatures/creepy-creatures-black-swallower.png'),
  'creepy-creatures-blue-dragon-sea-slug': require('../assets/creatures/creepy-creatures-blue-dragon-sea-slug.png'),
  'creepy-creatures-blue-ringed-octopus': require('../assets/creatures/creepy-creatures-blue-ringed-octopus.png'),
  'creepy-creatures-bombardier-beetle': require('../assets/creatures/creepy-creatures-bombardier-beetle.png'),
  'creepy-creatures-botfly-larva': require('../assets/creatures/creepy-creatures-botfly-larva.png'),
  'creepy-creatures-brain-worm': require('../assets/creatures/creepy-creatures-brain-worm.png'),
  'creepy-creatures-bristle-worm': require('../assets/creatures/creepy-creatures-bristle-worm.png'),
  'creepy-creatures-bullet-ant': require('../assets/creatures/creepy-creatures-bullet-ant.png'),
  'creepy-creatures-candiru-fish': require('../assets/creatures/creepy-creatures-candiru-fish.png'),
  'creepy-creatures-cassowary': require('../assets/creatures/creepy-creatures-cassowary.png'),
  'creepy-creatures-cone-snail': require('../assets/creatures/creepy-creatures-cone-snail.png'),
  'creepy-creatures-deathstalker-scorpion': require('../assets/creatures/creepy-creatures-deathstalker-scorpion.png'),
  'creepy-creatures-deep-sea-lizardfish': require('../assets/creatures/creepy-creatures-deep-sea-lizardfish.png'),
  'creepy-creatures-electric-eel': require('../assets/creatures/creepy-creatures-electric-eel.png'),
  'creepy-creatures-eyeless-spider': require('../assets/creatures/creepy-creatures-eyeless-spider.png'),
  'creepy-creatures-flesh-fly': require('../assets/creatures/creepy-creatures-flesh-fly.png'),
  'creepy-creatures-flying-snake': require('../assets/creatures/creepy-creatures-flying-snake.png'),
  'creepy-creatures-gharial': require('../assets/creatures/creepy-creatures-gharial.png'),
  'creepy-creatures-giant-isopod': require('../assets/creatures/creepy-creatures-giant-isopod.png'),
  'creepy-creatures-goblin-shark': require('../assets/creatures/creepy-creatures-goblin-shark.png'),
  'creepy-creatures-goliath-birdeater': require('../assets/creatures/creepy-creatures-goliath-birdeater.png'),
  'creepy-creatures-goliath-tigerfish': require('../assets/creatures/creepy-creatures-goliath-tigerfish.png'),
  'creepy-creatures-guinea-worm': require('../assets/creatures/creepy-creatures-guinea-worm.png'),
  'creepy-creatures-hag-moth-caterpillar': require('../assets/creatures/creepy-creatures-hag-moth-caterpillar.png'),
  'creepy-creatures-hagfish': require('../assets/creatures/creepy-creatures-hagfish.png'),
  'creepy-creatures-hammerhead-worm': require('../assets/creatures/creepy-creatures-hammerhead-worm.png'),
  'creepy-creatures-harlequin-toad': require('../assets/creatures/creepy-creatures-harlequin-toad.png'),
  'creepy-creatures-hooded-pitohui': require('../assets/creatures/creepy-creatures-hooded-pitohui.png'),
  'creepy-creatures-horse-botfly': require('../assets/creatures/creepy-creatures-horse-botfly.png'),
  'creepy-creatures-horsehair-worm': require('../assets/creatures/creepy-creatures-horsehair-worm.png'),
  'creepy-creatures-hypnotic-stargazer-worm': require('../assets/creatures/creepy-creatures-hypnotic-stargazer-worm.png'),
  'creepy-creatures-immortal-jellyfish': require('../assets/creatures/creepy-creatures-immortal-jellyfish.png'),
  'creepy-creatures-inland-taipan': require('../assets/creatures/creepy-creatures-inland-taipan.png'),
  'creepy-creatures-japanese-spider-crab': require('../assets/creatures/creepy-creatures-japanese-spider-crab.png'),
  'creepy-creatures-kissing-bug': require('../assets/creatures/creepy-creatures-kissing-bug.png'),
  'creepy-creatures-komodo-dragon': require('../assets/creatures/creepy-creatures-komodo-dragon.png'),
  'creepy-creatures-lamprey': require('../assets/creatures/creepy-creatures-lamprey.png'),
  'creepy-creatures-maggot-of-the-flesh-fly': require('../assets/creatures/creepy-creatures-maggot-of-the-flesh-fly.png'),
  'creepy-creatures-mouth-brooding-fish': require('../assets/creatures/creepy-creatures-mouth-brooding-fish.png'),
  'creepy-creatures-musk-ox-parasite-fly': require('../assets/creatures/creepy-creatures-musk-ox-parasite-fly.png'),
  'creepy-creatures-nose-horned-viper': require('../assets/creatures/creepy-creatures-nose-horned-viper.png'),
  'creepy-creatures-parasitic-barnacle': require('../assets/creatures/creepy-creatures-parasitic-barnacle.png'),
  'creepy-creatures-peacock-mantis-shrimp': require('../assets/creatures/creepy-creatures-peacock-mantis-shrimp.png'),
  'creepy-creatures-pistol-shrimp': require('../assets/creatures/creepy-creatures-pistol-shrimp.png'),
  'creepy-creatures-poison-dart-frog': require('../assets/creatures/creepy-creatures-poison-dart-frog.png'),
  'creepy-creatures-rat-tailed-maggot': require('../assets/creatures/creepy-creatures-rat-tailed-maggot.png'),
  'creepy-creatures-red-paper-wasp': require('../assets/creatures/creepy-creatures-red-paper-wasp.png'),
  'creepy-creatures-saddleback-caterpillar': require('../assets/creatures/creepy-creatures-saddleback-caterpillar.png'),
  'creepy-creatures-scaly-foot-snail': require('../assets/creatures/creepy-creatures-scaly-foot-snail.png'),
  'creepy-creatures-sea-cucumber': require('../assets/creatures/creepy-creatures-sea-cucumber.png'),
  'creepy-creatures-sea-devil-anglerfish': require('../assets/creatures/creepy-creatures-sea-devil-anglerfish.png'),
  'creepy-creatures-sea-spider': require('../assets/creatures/creepy-creatures-sea-spider.png'),
  'creepy-creatures-spiny-oak-slug-caterpillar': require('../assets/creatures/creepy-creatures-spiny-oak-slug-caterpillar.png'),
  'creepy-creatures-stargazer-fish': require('../assets/creatures/creepy-creatures-stargazer-fish.png'),
  'creepy-creatures-stink-bug': require('../assets/creatures/creepy-creatures-stink-bug.png'),
  'creepy-creatures-stonefish': require('../assets/creatures/creepy-creatures-stonefish.png'),
  'creepy-creatures-surinam-toad': require('../assets/creatures/creepy-creatures-surinam-toad.png'),
  'creepy-creatures-terrible-claw-lobster': require('../assets/creatures/creepy-creatures-terrible-claw-lobster.png'),
  'creepy-creatures-tiger-leech': require('../assets/creatures/creepy-creatures-tiger-leech.png'),
  'creepy-creatures-tongue-worm': require('../assets/creatures/creepy-creatures-tongue-worm.png'),
  'creepy-creatures-tongue-eating-louse': require('../assets/creatures/creepy-creatures-tongue-eating-louse.png'),
  'creepy-creatures-tsetse-fly': require('../assets/creatures/creepy-creatures-tsetse-fly.png'),
  'creepy-creatures-vampire-bat': require('../assets/creatures/creepy-creatures-vampire-bat.png'),
  'creepy-creatures-vampire-fish-payara': require('../assets/creatures/creepy-creatures-vampire-fish-payara.png'),
  'creepy-creatures-velvet-worm': require('../assets/creatures/creepy-creatures-velvet-worm.png'),
  'creepy-creatures-zombie-ant-fungus': require('../assets/creatures/creepy-creatures-zombie-ant-fungus.png'),
  'creepy-creatures-zombie-snail': require('../assets/creatures/creepy-creatures-zombie-snail.png'),
  'creepy-creatures-zombie-starfish': require('../assets/creatures/creepy-creatures-zombie-starfish.png'),

  // ─── Creepy Dinosaurs (80) ───────────────────────────────────────────────
  'creepy-dinosaurs-t-rex': require('../assets/creatures/dinosaurs/T. rex.jpeg'),
  'creepy-dinosaurs-tarbosaurus': require('../assets/creatures/dinosaurs/Tarbosaurus.png'),
  'creepy-dinosaurs-albertosaurus': require('../assets/creatures/dinosaurs/Albertosaurus.jpeg'),
  'creepy-dinosaurs-giganotosaurus': require('../assets/creatures/dinosaurs/Giganotosaurus.jpeg'),
  'creepy-dinosaurs-allosaurus': require('../assets/creatures/dinosaurs/Allosaurus.png'),
  'creepy-dinosaurs-ceratosaurus': require('../assets/creatures/dinosaurs/Ceratosaurus.png'),
  'creepy-dinosaurs-carnotaurus': require('../assets/creatures/dinosaurs/Carnotaurus.png'),
  'creepy-dinosaurs-majungasaurus': require('../assets/creatures/dinosaurs/Majungasaurus.png'),
  'creepy-dinosaurs-dilophosaurus': require('../assets/creatures/dinosaurs/Dilophosaurus.png'),
  'creepy-dinosaurs-spinosaurus': require('../assets/creatures/dinosaurs/Spinosaurus.png'),
  'creepy-dinosaurs-baryonyx': require('../assets/creatures/dinosaurs/Baryonyx.png'),
  'creepy-dinosaurs-suchomimus': require('../assets/creatures/dinosaurs/Suchomimus.png'),
  'creepy-dinosaurs-irritator': require('../assets/creatures/dinosaurs/Irritator.jpeg'),
  'creepy-dinosaurs-deinonychus': require('../assets/creatures/dinosaurs/Deinonychus.png'),
  'creepy-dinosaurs-velociraptor': require('../assets/creatures/dinosaurs/Velociraptor.png'),
  'creepy-dinosaurs-utahraptor': require('../assets/creatures/dinosaurs/Utahraptor.png'),
  'creepy-dinosaurs-microraptor': require('../assets/creatures/dinosaurs/Microraptor.png'),
  'creepy-dinosaurs-archaeopteryx': require('../assets/creatures/dinosaurs/Archaeopteryx.png'),
  'creepy-dinosaurs-ankylosaurus': require('../assets/creatures/dinosaurs/Ankylosaurus.png'),
  'creepy-dinosaurs-euoplocephalus': require('../assets/creatures/dinosaurs/Euoplocephalus.png'),
  'creepy-dinosaurs-borealopelta': require('../assets/creatures/dinosaurs/Borealopelta.png'),
  'creepy-dinosaurs-stegosaurus': require('../assets/creatures/dinosaurs/Stegosaurus.png'),
  'creepy-dinosaurs-kentrosaurus': require('../assets/creatures/dinosaurs/Kentrosaurus.png'),
  'creepy-dinosaurs-triceratops': require('../assets/creatures/dinosaurs/Triceratops.jpeg'),
  'creepy-dinosaurs-styracosaurus': require('../assets/creatures/dinosaurs/Styracosaurus.jpeg'),
  'creepy-dinosaurs-pachyrhinosaurus': require('../assets/creatures/dinosaurs/Pachyrhinosaurus.jpeg'),
  'creepy-dinosaurs-protoceratops': require('../assets/creatures/dinosaurs/Protoceratops.png'),
  'creepy-dinosaurs-psittacosaurus': require('../assets/creatures/dinosaurs/Psittacosaurus.png'),
  'creepy-dinosaurs-parasaurolophus': require('../assets/creatures/dinosaurs/Parasaurolophus.jpeg'),
  'creepy-dinosaurs-corythosaurus': require('../assets/creatures/dinosaurs/Corythosaurus.png'),
  'creepy-dinosaurs-edmontosaurus': require('../assets/creatures/dinosaurs/Edmontosaurus.png'),
  'creepy-dinosaurs-iguanodon': require('../assets/creatures/dinosaurs/Iguanodon.png'),
  'creepy-dinosaurs-ouranosaurus': require('../assets/creatures/dinosaurs/Ouranosaurus.png'),
  'creepy-dinosaurs-gallimimus': require('../assets/creatures/dinosaurs/Gallimimus.png'),
  'creepy-dinosaurs-oviraptor': require('../assets/creatures/dinosaurs/Oviraptor.png'),
  'creepy-dinosaurs-anzu': require('../assets/creatures/dinosaurs/Anzu.png'),
  'creepy-dinosaurs-gigantoraptor': require('../assets/creatures/dinosaurs/Gigantoraptor.png'),
  'creepy-dinosaurs-therizinosaurus': require('../assets/creatures/dinosaurs/Therizinosaurus.jpeg'),
  'creepy-dinosaurs-deinocheirus': require('../assets/creatures/dinosaurs/Deinocheirus.png'),
  'creepy-dinosaurs-compsognathus': require('../assets/creatures/dinosaurs/Compsognathus.png'),
  'creepy-dinosaurs-sinosauropteryx': require('../assets/creatures/dinosaurs/Sinosauropteryx.png'),
  'creepy-dinosaurs-yi-qi': require('../assets/creatures/dinosaurs/Yi qi.png'),
  'creepy-dinosaurs-kulindadromeus': require('../assets/creatures/dinosaurs/Kulindadromeus.png'),
  'creepy-dinosaurs-pachycephalosaurus': require('../assets/creatures/dinosaurs/Pachycephalosaurus.png'),
  'creepy-dinosaurs-stygimoloch': require('../assets/creatures/dinosaurs/Stygimoloch.png'),
  'creepy-dinosaurs-diplodocus': require('../assets/creatures/dinosaurs/Diplodocus.png'),
  'creepy-dinosaurs-apatosaurus': require('../assets/creatures/dinosaurs/Apatosaurus.png'),
  'creepy-dinosaurs-brachiosaurus': require('../assets/creatures/dinosaurs/Brachiosaurus.png'),
  'creepy-dinosaurs-giraffatitan': require('../assets/creatures/dinosaurs/Giraffatitan.png'),
  'creepy-dinosaurs-mamenchisaurus': require('../assets/creatures/dinosaurs/Mamenchisaurus.jpeg'),
  'creepy-dinosaurs-argentinosaurus': require('../assets/creatures/dinosaurs/Argentinosaurus.jpeg'),
  'creepy-dinosaurs-patagotitan': require('../assets/creatures/dinosaurs/Patagotitan.png'),
  'creepy-dinosaurs-saltasaurus': require('../assets/creatures/dinosaurs/Saltasaurus.png'),
  'creepy-dinosaurs-shunosaurus': require('../assets/creatures/dinosaurs/Shunosaurus.png'),
  'creepy-dinosaurs-amargasaurus': require('../assets/creatures/dinosaurs/Amargasaurus.png'),
  'creepy-dinosaurs-nigersaurus': require('../assets/creatures/dinosaurs/Nigersaurus.png'),
  'creepy-dinosaurs-dreadnoughtus': require('../assets/creatures/dinosaurs/Dreadnoughtus.png'),
  'creepy-dinosaurs-plateosaurus': require('../assets/creatures/dinosaurs/Plateosaurus.png'),
  'creepy-dinosaurs-coelophysis': require('../assets/creatures/dinosaurs/Coelophysis.png'),
  'creepy-dinosaurs-tooth-conveyor': require('../assets/creatures/dinosaurs/Tooth Conveyor.jpeg'),
  'creepy-dinosaurs-bite-scars': require('../assets/creatures/dinosaurs/Bite Scars.jpeg'),
  'creepy-dinosaurs-poop-fossil': require('../assets/creatures/dinosaurs/Poop Fossil.jpeg'),
  'creepy-dinosaurs-vomit-rock': require('../assets/creatures/dinosaurs/Vomit Rock.jpeg'),
  'creepy-dinosaurs-stone-stomachs': require('../assets/creatures/dinosaurs/Stone Stomachs.jpeg'),
  'creepy-dinosaurs-egg-pores': require('../assets/creatures/dinosaurs/Egg Pores.jpeg'),
  'creepy-dinosaurs-nest-cities': require('../assets/creatures/dinosaurs/Nest Cities.jpeg'),
  'creepy-dinosaurs-amber-tick': require('../assets/creatures/dinosaurs/Amber Tick.jpeg'),
  'creepy-dinosaurs-feather-fuzz': require('../assets/creatures/dinosaurs/Feather Fuzz.jpeg'),
  'creepy-dinosaurs-uv-patterns': require('../assets/creatures/dinosaurs/UV Patterns.jpeg'),
  'creepy-dinosaurs-air-sacs': require('../assets/creatures/dinosaurs/Air Sacs.jpeg'),
  'creepy-dinosaurs-hollow-bones': require('../assets/creatures/dinosaurs/Hollow Bones.jpeg'),
  'creepy-dinosaurs-trackway-chase': require('../assets/creatures/dinosaurs/Trackway Chase.jpeg'),
  'creepy-dinosaurs-mud-trap': require('../assets/creatures/dinosaurs/Mud Trap.jpeg'),
  'creepy-dinosaurs-bonebed-hill': require('../assets/creatures/dinosaurs/Bonebed Hill.jpeg'),
  'creepy-dinosaurs-ash-blanket': require('../assets/creatures/dinosaurs/Ash Blanket.jpeg'),
  'creepy-dinosaurs-flood-pile': require('../assets/creatures/dinosaurs/Flood Pile.jpeg'),
  'creepy-dinosaurs-dino-burrows': require('../assets/creatures/dinosaurs/Dino Burrows.jpeg'),
  'creepy-dinosaurs-egg-guardians': require('../assets/creatures/dinosaurs/Egg Guardians.jpeg'),
  'creepy-dinosaurs-dino-breath': require('../assets/creatures/dinosaurs/Dino Breath.jpeg'),
  'creepy-dinosaurs-extinction-night': require('../assets/creatures/dinosaurs/Extinction Night.jpeg'),

  // ─── Creepy Earth (79) ───────────────────────────────────────────────────
  'creepy-earth-blood-falls': require('../assets/creatures/earth/Blood Falls.png'),
  'creepy-earth-brain-eating-amoeba': require('../assets/creatures/earth/Brain-Eating Amoeba.png'),
  'creepy-earth-poop-transplants': require('../assets/creatures/earth/Poop Transplants.png'),
  'creepy-earth-the-acid-clouds-of-java': require('../assets/creatures/earth/The Acid Clouds of Java.png'),
  'creepy-earth-the-fatberg-of-london': require('../assets/creatures/earth/The Fatberg of London.png'),
  'creepy-earth-the-composting-human': require('../assets/creatures/earth/The Composting Human.png'),
  'creepy-earth-quicksand-pits': require('../assets/creatures/earth/Quicksand Pits.png'),
  'creepy-earth-belly-button-biodome': require('../assets/creatures/earth/Belly Button Biodome.png'),
  'creepy-earth-zombie-fungus': require('../assets/creatures/earth/Zombie Fungus.png'),
  'creepy-earth-lake-natrons-statue-victims': require('../assets/creatures/earth/Lake Natron\'s StatueS.png'),
  'creepy-earth-island-of-garbage': require('../assets/creatures/earth/Island of Garbage.png'),
  'creepy-earth-edible-insect-burgers': require('../assets/creatures/earth/Edible Insect Burgers.png'),
  'creepy-earth-the-pee-pool-problem': require('../assets/creatures/earth/The Pee Pool Problem.png'),
  'creepy-earth-flesh-melting-lake': require('../assets/creatures/earth/Flesh-Melting Lake.png'),
  'creepy-earth-buried-in-sludge': require('../assets/creatures/earth/Buried in Sludge.png'),
  'creepy-earth-snot-bubbles': require('../assets/creatures/earth/Snot Bubbles.png'),
  'creepy-earth-rusty-rain': require('../assets/creatures/earth/Rusty Rain.png'),
  'creepy-earth-shower-mold-explosion': require('../assets/creatures/earth/Shower Mold Explosion.png'),
  'creepy-earth-the-toothpaste-sandwich': require('../assets/creatures/earth/The Toothpaste Sandwich.png'),
  'creepy-earth-exploding-graveyards': require('../assets/creatures/earth/Exploding Graveyards.png'),
  'creepy-earth-toxic-foam-flood': require('../assets/creatures/earth/Toxic Foam Flood.png'),
  'creepy-earth-eye-eating-parasite': require('../assets/creatures/earth/Eye-Eating Parasite.png'),
  'creepy-earth-sludge-filled-basements': require('../assets/creatures/earth/Sludge-Filled Basements.png'),
  'creepy-earth-sewer-gas-explosions': require('../assets/creatures/earth/Sewer Gas Explosions.png'),
  'creepy-earth-vomit-comet': require('../assets/creatures/earth/Vomit Comet.png'),
  'creepy-earth-bubble-boils': require('../assets/creatures/earth/Bubble Boils.png'),
  'creepy-earth-rat-king': require('../assets/creatures/earth/Rat King.png'),
  'creepy-earth-skin-peeling-lake': require('../assets/creatures/earth/Skin-Peeling Lake.png'),
  'creepy-earth-the-leech-pool': require('../assets/creatures/earth/The Leech Pool.png'),
  'creepy-earth-corpse-blooms': require('../assets/creatures/earth/Corpse Blooms.png'),
  'creepy-earth-the-chernobyl-forest': require('../assets/creatures/earth/The Chernobyl Forest.png'),
  'creepy-earth-black-mayonnaise': require('../assets/creatures/earth/Black Mayonnaise.png'),
  'creepy-earth-brain-boil': require('../assets/creatures/earth/Brain Boil.png'),
  'creepy-earth-toxic-tumbleweeds': require('../assets/creatures/earth/Toxic Tumbleweeds.png'),
  'creepy-earth-bubblegut-bacteria': require('../assets/creatures/earth/Bubblegut Bacteria.png'),
  'creepy-earth-rust-blood': require('../assets/creatures/earth/Rust Blood.png'),
  'creepy-earth-spontaneous-showers': require('../assets/creatures/earth/Spontaneous Showers.png'),
  'creepy-earth-vomit-tunnel': require('../assets/creatures/earth/Vomit Tunnel.png'),
  'creepy-earth-the-boiling-river': require('../assets/creatures/earth/The Boiling River.png'),
  'creepy-earth-bacterial-brick-walls': require('../assets/creatures/earth/Bacterial Brick Walls.png'),
  'creepy-earth-bubble-wrap-earthquakes': require('../assets/creatures/earth/Bubble Wrap Earthquakes.png'),
  'creepy-earth-the-sizzling-sidewalk': require('../assets/creatures/earth/The Sizzling Sidewalk.png'),
  'creepy-earth-dirty-snow': require('../assets/creatures/earth/Dirty Snow.png'),
  'creepy-earth-flesheating-mudslides': require('../assets/creatures/earth/Flesheating Mudslides.png'),
  'creepy-earth-trash-avalanche': require('../assets/creatures/earth/Trash Avalanche.png'),
  'creepy-earth-alien-slime-rain': require('../assets/creatures/earth/Alien Slime Rain.png'),
  'creepy-earth-oil-boils': require('../assets/creatures/earth/Oil Boils.png'),
  'creepy-earth-the-slime-coast': require('../assets/creatures/earth/The Slime Coast.png'),
  'creepy-earth-burnt-toast-fog': require('../assets/creatures/earth/Burnt Toast Fog.png'),
  'creepy-earth-sewage-tsunami': require('../assets/creatures/earth/Sewage Tsunami.png'),
  'creepy-earth-foaming-gut-lakes': require('../assets/creatures/earth/Foaming Gut Lakes.png'),
  'creepy-earth-grease-trap-geyser': require('../assets/creatures/earth/Grease Trap Geyser.png'),
  'creepy-earth-flesh-rotting-fungi': require('../assets/creatures/earth/Flesh-Rotting Fungi.png'),
  'creepy-earth-pimpled-planet-surface': require('../assets/creatures/earth/Pimpled Planet Surface.png'),
  'creepy-earth-hot-garbage-rain': require('../assets/creatures/earth/Hot Garbage Rain.png'),
  'creepy-earth-rotting-tap-water': require('../assets/creatures/earth/Rotting Tap Water.png'),
  'creepy-earth-the-bubbly-battlefield': require('../assets/creatures/earth/The Bubbly Battlefield.png'),
  'creepy-earth-kitchen-sponge-swamp': require('../assets/creatures/earth/Kitchen Sponge Swamp.png'),
  'creepy-earth-concrete-pus': require('../assets/creatures/earth/Concrete Pus.png'),
  'creepy-earth-the-boneyard-flood': require('../assets/creatures/earth/The Boneyard Flood.png'),
  'creepy-earth-mummy-mushrooms': require('../assets/creatures/earth/Mummy Mushrooms.png'),
  'creepy-earth-ball-lightning-bloopers': require('../assets/creatures/earth/Ball Lightning Bloopers.png'),
  'creepy-earth-acid-rain-hair-day': require('../assets/creatures/earth/Acid Rain Hair Day.png'),
  'creepy-earth-the-sludge-volcano': require('../assets/creatures/earth/The Sludge Volcano.png'),
  'creepy-earth-the-crusty-carpet': require('../assets/creatures/earth/The Crusty Carpet.png'),
  'creepy-earth-radioactive-wolf-puke': require('../assets/creatures/earth/Radioactive Wolf Puke.png'),
  'creepy-earth-flesh-eating-street-bacteria': require('../assets/creatures/earth/Flesh-Eating Bacteria.png'),
  'creepy-earth-earthquake-toilet-floods': require('../assets/creatures/earth/Earthquake Toilet Floods.png'),
  'creepy-earth-cemetery-sinkholes': require('../assets/creatures/earth/Cemetery Sinkholes.png'),
  'creepy-earth-tapeworm-towns': require('../assets/creatures/earth/Tapeworm Towns.png'),
  'creepy-earth-sewer-ratsplosion': require('../assets/creatures/earth/Sewer Ratsplosion.png'),
  'creepy-earth-the-skin-loss-slide': require('../assets/creatures/earth/The Skin-Loss Slide.png'),
  'creepy-earth-underground-scream-pipes': require('../assets/creatures/earth/Underground Scream Pipes.png'),
  'creepy-earth-maggot-vents': require('../assets/creatures/earth/Maggot Vents.png'),
  'creepy-earth-exploding-whale-cleanup': require('../assets/creatures/earth/Exploding Whale Cleanup.png'),
  'creepy-earth-rotting-desert-fish-pits': require('../assets/creatures/earth/Rotting Desert Fish Pits.png'),
  'creepy-earth-stomach-eating-sea-foam': require('../assets/creatures/earth/Stomach-Eating Sea Foam.png'),
  'creepy-earth-the-wormfall-phenomenon': require('../assets/creatures/earth/The Wormfall Phenomenon.png'),
  'creepy-earth-tongue-leech-springs': require('../assets/creatures/earth/Tongue-Leech Springs.png'),

  // ─── Special Specimens (15) ───────────────────────────────────────────────
  'special-hairworm-puppet': require('../assets/creatures/special/Hairworm Puppet.jpeg'),
  'special-jewel-wasp-zombie-roach': require('../assets/creatures/special/Jewel Wasp Zombie Roach.jpeg'),
  'special-sacculina-crab-hijacker': require('../assets/creatures/special/Sacculina Crab Hijacker.jpeg'),
  'special-broodsac-snail-zombie': require('../assets/creatures/special/Broodsac Snail Zombie.jpeg'),
  'special-guinea-worm-exit': require('../assets/creatures/special/Guinea Worm Exit.jpeg'),
  'special-masiakasaurus': require('../assets/creatures/special/Masiakasaurus.jpeg'),
  'special-pegomastax': require('../assets/creatures/special/Pegomastax.jpeg'),
  'special-kosmoceratops': require('../assets/creatures/special/Kosmoceratops.jpeg'),
  'special-mononykus': require('../assets/creatures/special/Mononykus.jpeg'),
  'special-halszkaraptor': require('../assets/creatures/special/Halszkaraptor.jpeg'),
  'special-brinicle-death-finger': require('../assets/creatures/special/Brinicle Death Finger.jpeg'),
  'special-snottite-cave': require('../assets/creatures/special/Snottite Cave.jpeg'),
  'special-door-to-hell-crater': require('../assets/creatures/special/Door to Hell Crater.jpeg'),
  'special-underwater-brine-lake': require('../assets/creatures/special/Underwater Brine Lake.jpeg'),
  'special-movile-cave': require('../assets/creatures/special/Movile Cave.jpeg'),
};
